name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: docker test
      run: docker ps -a

    - name: docker v
      run: docker -v
